### ISSUE TITLE
Simplified TextView Wrapper for OpenSpritz

### ISSUE THREAD

**Issue by andrewgiang** [OnlyInAmerica/GlanceReader#2]
I created a simplified TextView wrapper that encapsulates the Spritzer object for easy integration. 

It can be found here: [SpritzTextView](https://github.com/andrewgiang/SpritzerTextView/blob/master/lib/src/main/java/com/andrewgiang/textspritzer/lib/SpritzerTextView.java)

If you would like I can submit a pull-request to your repo.

**Comment by OnlyInAmerica** [comment]
This is awesome! I've got to re-organize the project to contain separate library and app modules like you've done. Let me poke about and see how to best fold your work in.

**Comment by OnlyInAmerica** [comment]
Ok, got the app / library split merged. If you'd like to pull request your SpritzTextView I'd happily include it.

**Comment by andrewgiang** [comment]
This was merged in.
