### ISSUE TITLE
missing maven-metadata.xml]

### ISSUE THREAD

**Issue by alejandro-anv** [OnlyInAmerica/GlanceReader#22]
When compiling (under linux) I receive the following error:

<pre>
[anv@server OpenSpritz-Android (master)]$ ./gradlew --info
Starting Build
Settings evaluated using settings file '/home/anv/git/OpenSpritz-Android/settings.gradle'.
Projects loaded. Root project using build file '/home/anv/git/OpenSpritz-Android/build.gradle'.
Included projects: [root project 'OpenSpritz-Android', project ':app', project ':lib']
Evaluating root project 'OpenSpritz-Android' using build file '/home/anv/git/OpenSpritz-Android/build.gradle'.
Evaluating project ':app' using build file '/home/anv/git/OpenSpritz-Android/app/build.gradle'.
Evaluating project ':lib' using build file '/home/anv/git/OpenSpritz-Android/lib/build.gradle'.
Resource missing. [HTTP GET: http://repo1.maven.org/maven2/com/android/support/appcompat-v7/maven-metadata.xml]
Resource missing. [HTTP GET: http://repo1.maven.org/maven2/com/android/support/appcompat-v7/]

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> A problem occurred configuring project ':lib'.
   > Could not resolve all dependencies for configuration ':lib:_debugCompile'.
      > Could not find any version that matches com.android.support:appcompat-v7:+.
        Required by:
            OpenSpritz-Android:lib:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 5.451 secs
</pre>

**Comment by andrewgiang** [comment]
Open the SDK and make sure you have the Android Support Library and Android Support repository installed.

**Comment by OnlyInAmerica** [comment]
andrewgiang's comment should address your issue. I'm going to close this but feel free to clarify if there's in fact something else awry.
