### ISSUE TITLE
Give option to hide icons and notification bar

### ISSUE THREAD

**Issue by domesticatedviking** [OnlyInAmerica/GlanceReader#29]
Great work guys, seriously.   Apart from the rewind function that others have mentioned, what I'd really appreciate most would be ability to hide the system notification bar, and the three icons at the top of the screen.  These are distracting, especially when using the black theme in a dark room on an AMOLED display.  Also, it would be awesome if I could choose where the spritz window was located on the screen in case it was more comfortable to hold/read somewhere else. Thanks!

**Comment by OnlyInAmerica** [comment]
Good call. As of da5ee345 the ActionBar is hidden during playback, and the System UI is set to SYSTEM_UI_FLAG_LOW_PROFILE (dimmed) at all times. I couldn't think of a compelling reason to fiddle with the ActionBar mid-Spritz...
