### ISSUE TITLE
400: Invalid request cannot build with gradlew

### ISSUE THREAD

**Issue by hagope** [OnlyInAmerica/GlanceReader#46]
`400: Invalid request`  when running the build command:

`./gradlew assemble`

Here is the full error:

`Could not GET 'https://github.com/karussell/mvnrepo/raw/master/releases/com/android/support/appcompat-v7/'. Received status code 400 from server: Bad Request`

**Comment by OnlyInAmerica** [comment]
Did you download all the Android SDK dependencies listed in README.md?

Android SDK Build-tools 19.0.2+
Android SDK tools 22.3+
SDK Platform 19
Android Support Repository 4

**Comment by hagope** [comment]
So I didn't have the Android Support Repository, and that got me a bit further, however, now I'm caught on proguard, here's what I'm seeing:

```
Warning: there were 1574 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: there were 90 unresolved references to program class members.
         Your input classes appear to be inconsistent.
         You may need to recompile the code.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedprogramclassmember)
:app:proguardRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:proguardRelease'.
> java.io.IOException: Please correct the above warnings first.
```

**Comment by OnlyInAmerica** [comment]
From your command line run `./gradlew assembleDebug`. Assembling the release
apk will only work if you set up your signing variables in
gradle.properties. As you see I haven't yet configured the proguard rules, so if you do want to build a signed release apk, set `runProguard` to `false` in the app's `build.gradle`.

**Comment by hagope** [comment]
Ok got it, now its building, thank you!
