### ISSUE TITLE
Text is not Right-Weighted

### ISSUE THREAD

**Issue by Miserlou** [OnlyInAmerica/GlanceReader#7]
Text is currently centered. To be a true "Spritz" view, words should never have more than 3 or 4 letters to the left of the pivot point, regardless of word length.

I think this should be doable by adding [this logic](https://github.com/Miserlou/OpenSpritz/blob/master/spritz.js#L173) to the printWord function in Spritzer.java

**Comment by OnlyInAmerica** [comment]
Max of 4 chars before pivot in 95f0648d. I'll leave this open until we're sure this.is.perfect.

**Comment by Miserlou** [comment]
Woooooordddd up!

Is there a canonical test ePub? sc.epub didn't work the last time I built (but it worked on the build you gave me before)

**Comment by OnlyInAmerica** [comment]
Made some further improvements to the right-weighting in b258d4c2. See if it pleases.

**Comment by OnlyInAmerica** [comment]
Feel free to holler if this is still an issue.
