### ISSUE TITLE
Unsupported file

### ISSUE THREAD

**Issue by keelanc** [OnlyInAmerica/GlanceReader#9]
Haven't been able to open any epubs, from my own library and various internet sources.

**Comment by OnlyInAmerica** [comment]
Any way you could upload / email the troubled epub. dbro@dbro.pro

**Comment by keelanc** [comment]
Sent!

**Comment by OnlyInAmerica** [comment]
A quick fix in 1b30cbd9 may resolve this issue. Try the [latest build](https://github.com/OnlyInAmerica/OpenSpritz-Android/blob/master/app-release-signed.apk)

**Comment by keelanc** [comment]
It works! Though, it's lost the Google Drive functionality. Was that intentional? I didn't see any mention of deprecating it in the commits.

**Comment by OnlyInAmerica** [comment]
The app uses the standard system OPEN_DOCUMENT intent on Android 4.4 and ACTION_GET_CONTENT for older Androids. I can't think of any reason the app would be responsible for Google Drive disappearing. Feel free to open a new issue if that persists.
